Final_Project: main.o vector.o
			cc main.o vector.o -o Final_Project
main.o: main.c vector.h
			cc main.c -c
vector.o: vector.c vector.h
			cc vector.c -c
clean:
			rm Final_Projecct main.o vector.o
